version: '3.7'

services:
  php:
    build:
      context: .cloud/docker
    volumes:
      - ./:/srv/app
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:11.5-alpine
    environment:
      POSTGRES_DB: _symfony_scheduler_tasks
      POSTGRES_PASSWORD: root
      POSTGRES_USER: toor

  redis:
    image: redis:6.2-alpine
