name: Code style
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  php-cs-fixer:
    name: Code style with PHP ${{ matrix.php-versions }} - ${{ matrix.composer-dependencies }} dependencies
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: true
      matrix:
        php-versions: ['8.0', '8.1', '8.2']
        composer-dependencies: ['highest', 'lowest']
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: zip, redis, pcntl
        env:
          update: true

      - name: Install Composer dependencies
        uses: "ramsey/composer-install@v1"
        with:
          dependency-versions: ${{ matrix.composer-dependencies }}
          composer-options: "--prefer-stable --ignore-platform-reqs"

      - name: PHP CS Fixer
        run: php vendor/bin/php-cs-fixer fix --allow-risky=yes --dry-run
        env:
          PHP_CS_FIXER_IGNORE_ENV: 1
