name: Code style
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  php-cs-fixer:
    name: PHP CS Fixer
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
        env:
          update: true

      - name: Install Composer dependencies
        uses: "ramsey/composer-install@v1"
        with:
          dependency-versions: "highest"
          composer-options: "--prefer-stable"

      - name: PHP CS Fixer
        uses: docker://oskarstark/php-cs-fixer-ga
        with:
            args: --dry-run . --diff-format=udiff
