name: Code style
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  php-cs-fixer:
    name: PHP CS Fixer
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.1']
        composer-dependencies: ['highest']
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: zip, redis, pcntl
        env:
          update: true

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2
        with:
          dependency-versions: ${{ matrix.composer-dependencies }}
          composer-options: '--prefer-stable'

      - name: PHP CS Fixer
        run: php vendor/bin/php-cs-fixer fix --allow-risky=yes --dry-run
