name: Dagger - Style
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

env:
  DAGGER_LOG_FORMAT: plain

jobs:
  dagger:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: PHP-CS-Fixer
        uses: dagger/dagger-for-github@v2
        with:
          workdir: pkg/universe.dagger.io/examples/todoapp
          args: do php_cs_fixer --plan .cloud/dagger/scheduler_bundle.cue
