name: Daily
on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  scheduler_bundle:
    name: PHP ${{ matrix.php-versions }} - ${{ matrix.composer-dependencies }}
    # https://hub.docker.com/_/ubuntu/
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: true
      matrix:
        php-versions: ['7.4', '8.0']
        composer-dependencies: ['', 'lowest']
    services:
      redis:
        image: redis:6.0.0
        ports:
          - 6379:6379
    steps:
      # https://github.com/actions/checkout (official)
      - name: Checkout
        uses: actions/checkout@v2

      # https://github.com/shivammathur/setup-php (community)
      - name: Setup PHP, extensions and composer with shivammathur/setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: zip, xdebug, redis
          coverage: xdebug
        env:
          update: true

      # —— Composer️ —————————————————————————————————————————————————————
      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ matrix.composer-dependencies }}-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-${{ matrix.composer-dependencies }}-

      - name: Install Composer dependencies
        if: matrix.composer-dependencies == ''
        run: composer update --no-suggest

      - name: Install Composer dependencies - Lowest
        if: matrix.composer-dependencies == 'lowest'
        run: composer update --no-suggest --prefer-lowest

      # —— Security ——————————————————————————————————————————————————————
      - name: Run Snyk to check for vulnerabilities # See https://github.com/snyk/actions/tree/master/php
        uses: snyk/actions/php@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor

      # —— Style —————————————————————————————————————————————————————————
      - name: PHP-CS-FIXER
        uses: docker://oskarstark/php-cs-fixer-ga
        with:
          args: --allow-risky=yes --dry-run --diff-format=udiff .

      # —— Rector ————————————————————————————————————————————————————————
      - name: Rector
        run: php vendor/bin/rector --dry-run --clear-cache

      # —— Psalm —————————————————————————————————————————————————————————
      - name: Run Psalm
        run: php vendor/bin/psalm

      # —— PHPStan ———————————————————————————————————————————————————————
      - name: PHPStan
        run: php vendor/bin/phpstan analyze --xdebug

      # —— PHPUnit ———————————————————————————————————————————————————————
      - name: PHPUnit
        run: php vendor/bin/phpunit tests
        env:
          SCHEDULER_REDIS_DSN: redis://127.0.0.1:6379/_symfony_scheduler_tasks

      # —— Infection —————————————————————————————————————————————————————
      - name: Infection
        run: php vendor/bin/infection --no-progress --show-mutations --threads=4
        env:
          SCHEDULER_REDIS_DSN: redis://127.0.0.1:6379/_symfony_scheduler_tasks
          INFECTION_BADGE_API_KEY: ${{ secrets.INFECTION_BADGE_API_KEY }}
