name: Docker linting
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  php-cs-fixer:
    name: Docker linting - ${{ matrix.os }} OS
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: ['ubuntu-latest', 'macOS-latest']
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/checkout@v2
      - uses: hadolint/hadolint-action@v1.6.0
        with:
          dockerfile: .cloud/docker/Dockerfile
