name: Docker linting
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  docker-linting:
    name: Docker linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: hadolint/hadolint-action@v2.1.0
        with:
          dockerfile: .cloud/docker/Dockerfile
