name: Infection
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  infection:
    name: Infection with PHP ${{ matrix.php-versions }} - ${{ matrix.composer-dependencies }} dependencies
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true
      matrix:
        php-versions: ['7.4', '8.0']
        composer-dependencies: ['highest', 'lowest']
    services:
      redis:
        image: redis:6.0.0
        ports:
          - 6379:6379
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: zip, xdebug, redis
          coverage: xdebug
        env:
          update: true

      - name: Install Composer dependencies
        uses: "ramsey/composer-install@v1"
        with:
          dependency-versions: ${{ matrix.composer-dependencies }}
          composer-options: "--prefer-stable"

      - name: Run Infection
        run: php vendor/bin/infection --no-progress --min-covered-msi=80 --min-msi=75 --show-mutations --threads=4
        env:
          SCHEDULER_REDIS_DSN: redis://127.0.0.1:6379/_symfony_scheduler_tasks
