name: Infection
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  infection:
    name: Infection
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.1']
        composer-dependencies: ['highest']
    services:
      redis:
        image: redis:6.0.0
        ports:
          - 6379:6379
      postgres:
        image: postgres:9.4
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: zip, xdebug, redis
          coverage: xdebug
        env:
          update: true

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2
        with:
          dependency-versions: ${{ matrix.composer-dependencies }}
          composer-options: '--prefer-stable'

      - name: Run Infection
        run: php vendor/bin/infection --no-progress --show-mutations --threads=4
        env:
          SCHEDULER_REDIS_DSN: 'redis://127.0.0.1:6379/_symfony_scheduler_tasks'
          SCHEDULER_POSTGRES_DSN: 'postgres://postgres:postgres@127.0.0.1:5432/_symfony_scheduler_tasks'
          INFECTION_BADGE_API_KEY: ${{ secrets.INFECTION_BADGE_API_KEY }}
