name: Infection
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  infection:
    name: Infection with PHP ${{ matrix.php-versions }} - ${{ matrix.composer-dependencies }} dependencies - ${{ matrix.os }} OS
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        php-versions: ['8.0', '8.1']
        composer-dependencies: ['highest', 'lowest']
        postgres: ['9-alpine', '10-alpine', '11-alpine', '12-alpine', 'latest']
        mysql: ['5.7', '8.0']
        os: ['ubuntu-latest']
    services:
      redis:
        image: redis:6.0.0
        ports:
          - 6379:6379
      postgres:
        image: postgres:${{ matrix.postgres }}
        env:
          POSTGRES_PASSWORD: root
          POSTGRES_USER: toor
        ports:
          - 5432:5432
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: zip, xdebug, redis
          coverage: xdebug
        env:
          update: true

      - name: Install Composer dependencies
        uses: "ramsey/composer-install@v1"
        with:
          dependency-versions: ${{ matrix.composer-dependencies }}
          composer-options: "--prefer-stable"

      - name: Run Infection
        run: php vendor/bin/infection --no-progress --show-mutations --threads=4
        env:
          SCHEDULER_REDIS_DSN: 'redis://127.0.0.1:6379/_symfony_scheduler_tasks'
          INFECTION_BADGE_API_KEY: ${{ secrets.INFECTION_BADGE_API_KEY }}
