name: SchedulerBundle - Push
on: [push]
jobs:
  scheduler_bundle:
    name: PHP ${{ matrix.php-versions }} - ${{ matrix.composer-dependencies }}
    # https://hub.docker.com/_/ubuntu/
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: true
      matrix:
        php-versions: ['7.2', '7.3', '7.4', '8.0']
        phpunit-bridge-version: ['8.5', '8.5', '8.5', '9.5']
        composer-dependencies: ['', 'lowest']
    services:
      redis:
        image: redis:6.0.0
        ports:
          - 6379:6379
    steps:
      # https://github.com/actions/checkout (official)
      - name: Checkout
        uses: actions/checkout@v2

      # https://github.com/shivammathur/setup-php (community)
      - name: Setup PHP, extensions and composer with shivammathur/setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: zip, xdebug, redis
          coverage: xdebug
        env:
          update: true

      # —— Composer️ —————————————————————————————————————————————————————
      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ matrix.php-versions }}-${{ matrix.composer-dependencies }}-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-${{ matrix.php-versions }}-${{ matrix.composer-dependencies }}-

      - name: Install Composer dependencies
        if: matrix.composer-dependencies == ''
        run: composer update

      - name: Install Composer dependencies - Lowest
        if: matrix.composer-dependencies == 'lowest'
        run: composer update --prefer-lowest

      # —— Style —————————————————————————————————————————————————————————
      - name: PHP-CS-FIXER
        uses: docker://oskarstark/php-cs-fixer-ga
        with:
          args: --dry-run .

      # —— Rector ————————————————————————————————————————————————————————
      - name: Rector
        if: matrix.php-versions != '8.0'
        run: php vendor/bin/rector process --dry-run --clear-cache

      # —— PHPUnit ———————————————————————————————————————————————————————
      - name: PHPUnit
        run: php vendor/bin/phpunit tests
        env:
          SCHEDULER_REDIS_DSN: redis://127.0.0.1:6379/_symfony_scheduler_tasks
          SYMFONY_PHPUNIT_VERSION: ${{ matrix.phpunit-bridge-version }}

      - name: Cache PHPUnit result
        uses: actions/cache@v2
        with:
          path: ~/.phpunit.result.cache
          key: ${{ runner.os }}-phpunit-${{ matrix.php-versions }}-${{ hashFiles('**/.phpunit.result.cache') }}
          restore-keys: ${{ runner.os }}-phpunit-${{ matrix.php-versions }}-

      # —— Infection —————————————————————————————————————————————————————
      - name: Infection
        run: php vendor/bin/infection --no-progress --min-covered-msi=80 --min-msi=75 --show-mutations
        env:
          SCHEDULER_REDIS_DSN: redis://127.0.0.1:6379/_symfony_scheduler_tasks
          SYMFONY_PHPUNIT_VERSION: ${{ matrix.phpunit-bridge-version }}
