name: Security
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  security:
    name: Security with PHP ${{ matrix.php-versions }} - ${{ matrix.composer-dependencies }} dependencies - ${{ matrix.os }} OS
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        php-versions: ['8.0', '8.1']
        composer-dependencies: ['highest', 'lowest']
        os: ['ubuntu-latest']
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: zip, redis, pcntl
        env:
          update: true

      - name: Install Composer dependencies
        uses: "ramsey/composer-install@v1"
        with:
          dependency-versions: ${{ matrix.composer-dependencies }}
          composer-options: "--prefer-stable"

      - name: Run Snyk to check for vulnerabilities # See https://github.com/snyk/actions/tree/master/php
        uses: snyk/actions/php@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
